-- Create Database for BakeSmart
-- Run this in Laragon MySQL or any MySQL client

CREATE DATABASE IF NOT EXISTS prediksi_stok_kue;
USE prediksi_stok_kue;

-- Create tables will be auto-generated by Flask-SQLAlchemy
-- Just run: python run.py in the backend directory

SELECT 'Database created successfully!' as status;
